config-file = "xterm-ghostty"
# Load the default theme
config-file = ~/.config/ghostty/ghostty-theme

# Shader setup (pick one shader, or add more as needed)
custom-shader = shaders/bloom025.glsl



# Font settings
font-family = "JetBrainsMono Nerd Font"
font-size = 18

# macOS window decoration
macos-titlebar-style = hidden
background-opacity=0.7
background-blur=64

# Confirm before closing a surface (false means no confirmation)
confirm-close-surface = false

# Quick terminal settings
keybind = cmd+s=toggle_quick_terminal
quick-terminal-animation-duration = 0.08

# Keybindings for inspector and reloading config
keybind = super+i=inspector:toggle
keybind = super+r=reload_config

# macOS Option key behavior as Alt key
macos-option-as-alt = right



