"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
	# Hopping
	{ on = "u", run = "arrow prev" },
	{ on = "e", run = "arrow next" },

	{ on = "U", run = "arrow -5" },
	{ on = "E", run = "arrow 5" },

	# Navigation
	{ on = "n", run = "leave" },
	{ on = "i", run = "plugin smart-enter" },

	{ on = "N", run = "back" },
	{ on = "I", run = "forward" },

	# Seeking
	{ on = "<C-u>", run = "seek -5" },
	{ on = "<C-e>", run = "seek 5" },

	# Operation
	{ on = "l", run = "link" },
	{ on = "L", run = "link --relative" },

	# Find
	{ on = "-", run = "find_arrow" },
	{ on = "=", run = "find_arrow --previous" },

	# Goto
	{ on = [ "g", "r" ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"' },
	{ on = [ 'g', 'f' ], run = 'shell -- ya emit cd "$(zoxide query Friends)"' },
	{ on = [ "g", "c" ], run = "plugin vcs-files" },

	# Shell
	{ on = "$", run = 'shell --block $SHELL' },

	# Plugins
	{ on = "M",          run = "plugin mount" },
	{ on = "<C-d>",      run = "plugin diff" },
	{ on = [ "c", "m" ], run = "plugin chmod" },
	{ on = [ "b", "a" ], run = "plugin mactag add" },
	{ on = [ "b", "r" ], run = "plugin mactag remove" },
]

[tasks]

prepend_keymap = [
	{ on = "u", run = "arrow -1" },
	{ on = "e", run = "arrow 1" },
]

[spot]

prepend_keymap = [
	{ on = "u", run = "arrow -1" },
	{ on = "e", run = "arrow 1" },
	{ on = "n", run = "swipe -1" },
	{ on = "i", run = "swipe 1" },
]

[pick]

prepend_keymap = [
	{ on = "u", run = "arrow -1" },
	{ on = "e", run = "arrow 1" },
]

[input]

prepend_keymap = [
	# Mode
	{ on = "k",     run = "insert" },
	{ on = "<C-n>", run = [ "move bol", "insert" ] },
	{ on = "<C-i>", run = [ "move eol", "insert --append" ] },

	# Character-wise movement
	{ on = "n", run = "move -1" },
	{ on = "i", run = "move 1" },

	# Word-wise movement
	{ on = "h", run = "forward --end-of-word" },

	# Line-wise movement
	{ on = "N", run = "move bol" },
	{ on = "I", run = "move eol" },

	# Cut/Yank/Paste
	{ on = "x", run = [ "delete", "move 1 --in-operating" ] },

	# Undo/Redo
	{ on = "l", run = "undo" },
	{ on = "L", run = "redo" },
]

[confirm]

prepend_keymap = [
	{ on = "u", run = "arrow -1" },
	{ on = "e", run = "arrow 1" },
]

[cmp]

prepend_keymap = [
	{ on = "<C-u>", run = "arrow -1" },
	{ on = "<C-e>", run = "arrow 1" },
]

[help]

prepend_keymap = [
	# Navigation
	{ on = "u", run = "arrow -1" },
	{ on = "e", run = "arrow 1" },

	{ on = "U", run = "arrow -5" },
	{ on = "E", run = "arrow 5" },
]
