"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
linemode     = "size"
show_hidden  = true
sort_by      = "natural"
mouse_events = []

[preview]
wrap       = "yes"
max_width  = 1500
max_height = 1500

[input]
cursor_blink = true

[opener]
edit = [
	{ run = '${EDITOR:=vi} "$@"', desc = "$EDITOR", block = true },
	{ run = 'code "$@"', orphan = true },
]
play = [
	{ run = 'mpv --force-window "$@"' },
	{ run = 'iina --no-stdin "$@"' },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" }
]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here" },
	{ run = '/Applications/MacZip.app/Contents/MacOS/MacZip "$1"', orphan = true, desc = "MacZip" }
]
subtitle = [
	{ run = ''' echo sub-add "'$0'" | socat - /tmp/mpv.sock ''', desc = "Add sub to MPV" },
	{ run = ''' opencc -c tw2sp -i "$1" -o "$1" ''', desc = "TW to SC" },
]

[open]
prepend_rules = [
	{ name = "*.{ass,srt,ssa,sty,sup,vtt}", use = [ "subtitle", "edit" ] },
]

[plugin]
prepend_fetchers = [
	{ id = "git", name = "*", run = "git" },
	{ id = "git", name = "*/", run = "git" },

	{ id = "mactag", name = "*", run = "mactag" },
	{ id = "mactag", name = "*/", run = "mactag" },
]
